---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-api-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  # Basic Settings
  ACIDRAIN_LOG_LEVEL: '{{ .Values.log.level }}'
  ACIDRAIN_LOG_OUTPUT_FORMAT: '{{ .Values.log.output_format }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: dummy-db-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- if .Values.db.host }}
  DUMMY_API_DB_HOST: "{{ .Values.db.host | b64enc }}"
  {{- end }}
  {{- if .Values.db.port }}
  DUMMY_API_DB_PORT: "{{ .Values.db.port | toString | b64enc }}"
  {{- end }}
  {{- if .Values.db.name }}
  DUMMY_API_DB_NAME: "{{ .Values.db.name | b64enc }}"
  {{- end }}
  {{- if .Values.db.username }}
  DUMMY_API_DB_USERNAME: "{{ .Values.db.username | b64enc }}"
  {{- end }}
  {{- if .Values.db.password }}
  DUMMY_API_DB_PASSWORD: "{{ .Values.db.password | b64enc }}"
  {{- end }}
  {{- if .Values.db.pool_size }}
  DUMMY_API_DB_POOL_SIZE: "{{ .Values.db.pool_size | toString | b64enc }}"
  {{- end }}
