apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    org.acidrain.service: dummy-api
  name: dummy-api
spec:
  ports:
    - name: "http"
      port: {{ .Values.api.port }}
  selector:
    org.acidrain.service: dummy-api
status:
  loadBalancer: {}
